// Comments for autogenerated json, not currently used

/**
 * Add two numbers
 * @customfunction
 * @param {number} first First number
 * @param {number} second Second number
 * @returns {number} The sum of the two numbers.
 */
export function add(first, second) {
  return first + second + 10;
}

CustomFunctions.associate("ADD", add);
